# Generated by Django 3.1.7 on 2021-04-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210419_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='loan_status',
            field=models.BooleanField(default=False),
        ),
    ]
